name: Deploy TicTacToe Bot & Web App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # ============================================
  # Job 1: Build and Test
  # ============================================
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint || echo "Linter not configured yet"
      continue-on-error: true
      
    - name: Run tests
      run: npm test || echo "Tests not configured yet"
      continue-on-error: true
      
    - name: Build project
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "📦 Проверка результата сборки..."
        if [ -d "dist/bot" ]; then
          echo "✅ Bot build успешен"
          ls -la dist/bot/ | head -5
        fi
        if [ -d "dist/web" ]; then
          echo "✅ Web App build успешен"
          ls -la dist/web/ | head -5
        fi

  # ============================================
  # Job 2: Deploy Web App to Beget
  # ============================================
  deploy-web:
    name: Deploy Web App to Beget
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Web App
      run: npm run build:web
      
    - name: Verify build output
      run: |
        echo "📦 Проверка файлов для деплоя..."
        ls -la dist/web/
        if [ ! -f "dist/web/index.html" ]; then
          echo "❌ index.html не найден!"
          exit 1
        fi
        echo "✅ Файлы готовы к деплою"
      
    - name: Deploy Web App to Beget FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/web/
        server-dir: ${{ secrets.FTP_WEB_PATH }}/
        dangerous-clean-slate: false
        dry-run: false
        exclude: |
          **/.git*
          **/.git*/**
          **/.DS_Store
          **/Thumbs.db
          **/*.map
          **/.env*
        log-level: verbose
      
    - name: Deployment Success
      run: |
        echo "🎉 Web App успешно задеплоен на Beget!"
        echo "🌐 URL: https://develonik.ru/"
        echo "📅 Время: $(date)"

  # ============================================
  # Job 3: Deploy Bot to Beget (SSH)
  # ============================================
  deploy-bot:
    name: Deploy Bot to Beget
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Bot
      run: npm run build:bot
      
    - name: Verify bot build
      run: |
        echo "📦 Проверка сборки бота..."
        if [ -d "dist/bot" ]; then
          echo "✅ Bot build успешен"
          ls -la dist/bot/ | head -5
        else
          echo "❌ dist/bot не найден!"
          exit 1
        fi
      
    - name: Deploy Bot to Beget via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "dist/bot/*,package.json,package-lock.json"
        target: ${{ secrets.SSH_BOT_PATH }}
        strip_components: 0
      
    - name: Setup Bot on Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          cd ${{ secrets.SSH_BOT_PATH }}
          npm install --production
          pm2 restart tictactoe-bot || pm2 start dist/bot/index.js --name tictactoe-bot
          pm2 save
      
    - name: Bot Deployment Success
      run: |
        echo "🤖 Bot успешно задеплоен на Beget!"
        echo "📅 Время: $(date)"

